package com.cibermodelo.base.model

data class Field(
    val id: FieldType,
    val name: String
)

enum class FieldType {
    DECEASED_ADDRESS,
    DECEASED_ARL,
    DECEASED_BANKINGINSTITUTION,
    DECEASED_BIRTHDAY,
    DECEASED_EMAIL,
    DECEASED_EPS,
    DECEASED_IDENTITYDOCUMENT,
    DECEASED_IDENTITYDOCUMENTTYPE,
    DECEASED_LASTNAME,
    DECEASED_MARITALESTATUS,
    DECEASED_NAME,
    DECEASED_NATIONALITY,
    DECEASED_RETAIREMENTFUND,
    DECEASED_SEVERANCEFUND,
    DESEASED_DECEASEDDATE,
    DECEASED_GENDER,
    DECEASED_DOCUMENTS
}